---
- name: add {{ restund_user }} group
  group:
    name: "{{ restund_user }}"
    state: present
    system: true
  tags:
    - restund
  when: restund_user != 'root'

- name: add {{ restund_user }} user
  user:
    name: "{{ restund_user }}"
    shell: "/bin/false"
    group: "{{ restund_user }}"
    system: true
    createhome: false
  when: restund_user != 'root'
  tags:
    - restund

- name: create /etc/restund and /opt/restund
  file:
    path:  "{{ item }}"
    state: directory
    mode:  0755
    owner: "{{ restund_user }}"
    group: "{{ restund_user }}"
  with_items:
    - /etc/restund
    - /opt/restund
  tags:
    - restund

- name: Download restund aci file
  get_url:
    url: "{{ aci_base_url }}/restund/restund-{{ versions.restund }}_linux_amd64.aci"
    dest: "/opt/restund/restund-{{ versions.restund }}_linux_amd64.aci"

- name: install restund tls certificate
  copy:
    dest:    /etc/restund/restund.pem
    content: "{{ restund_tls_certificate }}"
    mode:    0440
    owner:   "{{ restund_user }}"
    group:   "{{ restund_user }}"
  when: restund_tls_certificate is defined
  tags:
    - restund

- name: restund.conf
  template:
    src:   templates/restund.conf.j2
    dest:  /etc/restund/restund.conf
    mode:  0440
    owner: "{{ restund_user }}"
    group: "{{ restund_user }}"
  tags:
    - restund

- name: install restund unit file
  template:
    src:   templates/restund.service.j2
    dest:  /lib/systemd/system/restund.service
    mode:  0644
    owner: root
    group: root
  notify:
    - systemctl daemon-reload
    # - restart restund # NOTE: Restarting restund should be done _manually_
    - rkt gc
    - rkt image gc
  tags:
    - restund

- service:
    name:    restund
    enabled: true
    state:   started
