---
- name: disable spawning of unneeded gettys
  systemd:
    name: "getty@{{ item }}.service"
    enabled: false
    masked: true
    state: stopped
  with_items: [ tty1, tty2, tty3, tty4, tty5, tty6 ]
