---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: true
      changed_when: false
      when: ansible_os_family == 'Debian'
    - name: import yaml to disable gettys.
      import_tasks: disable_getty.yml
  # vars:
  roles:
    - ansible-role-ntp
    - ansible-restund
  post_tasks:
    - name: show result nodes
      debug: "cool!"
